AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Backend for the PacTrivia App

Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    # The PermissionsBoundary allows users to safely develop with their function's permissions constrained
    # to their current application. All the functions and roles in this application have to include it and
    # it has to be manually updated when you add resources to your application.
    # More information in https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html
    PermissionsBoundary: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/${AppId}-${AWS::Region}-PermissionsBoundary'

  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"

Parameters:
  AppId:
    Type: String

Resources:
  ## Routes ##
  regDevice:
    Type: AWS::Serverless::Function
    Properties:
      Handler: reg_device.lambda_handler
      Runtime: python3.12
      CodeUri: ./src
      Description: Used to generate a user token on first app launch.
      MemorySize: 128
      Timeout: 30
      Architectures:
        - arm64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserData
      Environment:
        Variables:
          USER_TABLE: !Ref UserData
      Events:
        Api:
          Type: Api
          Properties:
            Path: /regDevice
            Method: POST

  ## DynamoDB Tables ##
  UserData:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: B
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  Questions:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: team
          AttributeType: S
        - AttributeName: sk
          AttributeType: B
      KeySchema:
        - AttributeName: team
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
